In [3]:
import numpy
arr=numpy.array([1,3,4,5,6])
print(arr)

[1 3 4 5 6]


In [11]:
import numpy as np
arr=np.array([1,2,4,6,7])
print(arr)
print("Array Type : ",type(arr))

[1 2 4 6 7]
Array Type :  <class 'numpy.ndarray'>


## Numpy Version : 

In [8]:
import numpy
print(numpy.__version__)

1.20.3


## 0-D Arrays : 

In [2]:
import numpy as np
arr=np.array(130)
print(arr)

130


## 1-D Arrays : 

In [4]:
import numpy as np
arr=np.array([1,2,4,6,7])
print(arr)

[1 2 4 6 7]


## 2-D Arrays : 

In [6]:
import numpy as np
arr=np.array([[1,3,5],[2,4,6]])
print(arr)

[[1 3 5]
 [2 4 6]]


## 3-D Arrays :

In [11]:
import numpy as np
arr=np.array([[[1,3,5],[2,4,6]],[[100,1000,10000],[10,20,30]]])
print(arr)

[[[    1     3     5]
  [    2     4     6]]

 [[  100  1000 10000]
  [   10    20    30]]]


## Number of Dimensions (ndim) : 

In [11]:
import numpy as np
a1=np.array(130)
a2=np.array([1,2,3,5,6])
a3=np.array([[1,3,5],[2,4,6]])
a4=np.array([[[1,3,5],[2,4,6],[100,1000,10000]]])
print(a1.ndim," Dimensions")
print(a2.ndim," Dimensions")
print(a3.ndim," Dimensions")
print(a4.ndim," Dimensions")

0  Dimensions
1  Dimensions
2  Dimensions
3  Dimensions


## Higher Dimensional Arrays : 

In [16]:
import numpy as np
arr=np.array([1,4,6,7,8],ndmin=5)
print(arr)
print("Number of Dimensions : ",arr.ndim)

[[[[[1 4 6 7 8]]]]]
Number of Dimensions :  5


## arr = np.array([1, 2, 3, 4], ndmin=5)--->> Output : 5 Dimensions & [[[[[1 2 3 4]]]]]
In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

#    NumPy Array Indexing 

In [5]:
import numpy as np
arr=np.array([1,3,4,6,7])
print("The Element of 1st Position : ",arr[0],"\nThe Element of 4th Position : ",arr[3],"\nThe Element of 5th Position : ",arr[4])

The Element of 1st Position :  1 
The Element of 4th Position :  6 
The Element of 5th Position :  7


## Access 2-D Arrays : 

In [15]:
import numpy as np
arr=np.array([[1,3,5],[2,130,6]])
print("The element of second row and second column : ",arr[1,1])

The element of second row and second column :  130


## Access 3-D Arrays : 

In [30]:
import numpy as Firoz3D
arr=Firoz3D.array([[[1,3,5],[2,4,6]],[[100,1000,10000],[100000,3,4]],[[11,22,33],[129,130,131]]])
print(arr[2,1,1])

130


## Negative Indexing : 

In [35]:
import numpy as np
Firoz=np.array([[1,3,5],[2,4,6]])
print(Firoz[1,-1]," ",Firoz[1,-2]," ",Firoz[1,-3])

6   4   2


# NumPy Array Slicing

In [55]:
import numpy as np
arr=np.array([1,2,5,6,8,10,13])
print(arr[1:4])
print(arr[-2:-1])
print(arr[0:6:2])
print(arr[0::2])
print(arr[0::3])
print("Slice elements from beginning to 4(First four element's): ",arr[:4])
print("Slice elements from beginning to end : ",arr[:])
print("Print one element after one element : ",arr[: :2])

[2 5 6]
[10]
[1 5 8]
[ 1  5  8 13]
[ 1  6 13]
Slice elements from beginning to 4(First four element's):  [1 2 5 6]
Slice elements from beginning to end :  [ 1  2  5  6  8 10 13]
Print one element after one element :  [ 1  5  8 13]


## Slicing 2-D Arrays : 

In [63]:
import numpy as np
arr=np.array([[1,3,5],[2,4,6]])
print(arr[0,0:])
print(arr[0:1,2])
print(arr[0:2,1])
print(arr[0:2,0:2])
print(arr[0:2,:])
print(arr[:2,1:])
print(arr[:,:])

[1 3 5]
[5]
[3 4]
[[1 3]
 [2 4]]
[[1 3 5]
 [2 4 6]]
[[3 5]
 [4 6]]
[[1 3 5]
 [2 4 6]]
