# NumPy Array Reshaping

## (i) Reshape From 1-D to 2-D : 

In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("1-D array : ",arr)
print("The shape of arr : ",arr.shape)
arr1=arr.reshape(3,4)
print("2-D : ",arr1)
print("The shape of array arr1 : ",arr1.shape)

1-D array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
The shape of arr :  (12,)
2-D :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The shape of array arr1 :  (3, 4)


## (ii) Reshape From 1-D to 3-D : 

In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("1-D : ",arr)
ThreeD=arr.reshape(2,3,2)
print("3-D : ",ThreeD)
print("Shape of array ThreeD : ",ThreeD.shape)

1-D :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
3-D :  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape of array ThreeD :  (2, 3, 2)


## Can We Reshape Into any Shape?
### We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
rsp=arr.reshape(2,4)
print(rsp)
print("We can not reshape elements into dimensions unequally : ")
uneql=arr.reshape(3,3)
print(uneql)

[[1 2 3 4]
 [5 6 7 8]]
We can not reshape elements into dimensions unequally : 


ValueError: cannot reshape array of size 8 into shape (3,3)

## Returns Copy or View? --->> base atribute.
### The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array. copy() return None otherwise view() returns the original array.

In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
rsp=arr.reshape(2,3)
print("arr : ",arr.base)
print("rsp : ",rsp.base)

arr :  None
rsp :  [1 2 3 4 5 6]


In [35]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Monose Sarker : ",arr)
print(arr.reshape(3,2,2))
print(arr.reshape(3,2,2).base)
print("The example above returns the original array, so it is a view.")

Monose Sarker :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
The example above returns the original array, so it is a view.


## Unknown Dimension : 

In [31]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print("A new dimensional array : \n",arr.reshape(2,2,-1))
print("A new dimensional array : \n",arr.reshape(2,-1,4))
print("A new dimensional array : \n",arr.reshape(-1,2,4))

A new dimensional array : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
A new dimensional array : 
 [[[1 2 3 4]]

 [[5 6 7 8]]]
A new dimensional array : 
 [[[1 2 3 4]
  [5 6 7 8]]]


### We can not pass -1 to more than one dimension.

In [32]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape(3,-1,-1))

ValueError: can only specify one unknown dimension

## Flattening the arrays :
### Flattening array means converting a multidimensional array into a 1D array.
### We can use reshape(-1) to do this.

In [42]:
import numpy as np
arr=np.array([[[1,4,6],[10,20,40]],[[100,400,600],[1000,2000,4000]]])
print("Before flattening the array : \n",arr)
print("After flattening the array : \n",arr.reshape(-1))

Before flattening the array : 
 [[[   1    4    6]
  [  10   20   40]]

 [[ 100  400  600]
  [1000 2000 4000]]]
After flattening the array : 
 [   1    4    6   10   20   40  100  400  600 1000 2000 4000]
