# NumPy Array Iterating

## (i) 1-D Array : 

In [5]:
import numpy as np
arr=np.array([1,2,4,5,6])
for x in arr:
    print(x)

1
2
4
5
6


## (ii) 2-D Array : 

In [6]:
import numpy as np
arr=np.array([[1,3,4],[4,5,7]])
for x in arr:
    print(x)

[1 3 4]
[4 5 7]


In [16]:
import numpy as np
arr=np.array([[1,2,3],[4,5,7]])
for x in arr:
    for y in x: 
        print(y)

1
2
3
4
5
7


## (iii) 3-D Array : 

In [25]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ThreeD=arr.reshape(2,2,3)
for x in ThreeD:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [26]:
import numpy as np
arr=np.array([[[2,4,6],[1,3,5]],[[8,10,12],[7,9,11]]])
print("Return the actual values, the scalars : ")
for x in arr:
    for y in x:
        for z in y:
            print(z)
print("Print into the 2-D elements : ")
for x in arr:
    for y in x:
        print(y)
print("Print into the 3-D elements : ")
for x in arr:
    print(x)

Return the actual values, the scalars : 
2
4
6
1
3
5
8
10
12
7
9
11
Print into the 2-D elements : 
[2 4 6]
[1 3 5]
[ 8 10 12]
[ 7  9 11]
Print into the 3-D elements : 
[[2 4 6]
 [1 3 5]]
[[ 8 10 12]
 [ 7  9 11]]


## Iterating Each Scalar Element into the Array Using nditer() : Avoid Heigher Dimensions

In [29]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(arr)
print("Printing each scalar elements : ")
for x in np.nditer(arr):
    print(x)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Printing each scalar elements : 
1
2
3
4
5
6
7
8
9
10
11
12
